In [2]:
import numpy as np

In [3]:
a = np.array([1, 2, 3])
m = np.array([[1,2],[3,4]])

In [4]:
a = np.array([1,2,3])
m = np.array([[1,2],[3,4]])


In [7]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [18]:
np.random.rand(3,3)       

array([[0.07530676, 0.35235682, 0.87650043],
       [0.38367435, 0.39909373, 0.1329385 ],
       [0.67591253, 0.73120245, 0.4300439 ]])

In [22]:
np.random.randn(2,2)

array([[-0.88099696,  0.88193053],
       [ 0.11753666, -0.76920321]])

In [35]:
np.random.randint(1,20,(4,4))

array([[ 4, 18,  5, 17],
       [19,  7,  1,  8],
       [ 5, 18, 10, 12],
       [ 9, 16, 13,  1]], dtype=int32)

In [36]:
np.arange(0,14,3)

array([ 0,  3,  6,  9, 12])

In [37]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [42]:
b = np.array([[1,2,3],[4,4,5],[7,8,9]])

In [56]:
b[0,1]
print(b[0,1])

2


In [58]:
b[:,2]
print(b[:,2])

[3 5 9]


In [59]:
b[2,:]
print(b[2,:])

[7 8 9]


In [60]:
b[0:1,1:2]
print(b[0:1,1:2])

[[2]]


In [64]:
b[b > 25]
print(b[b > 1])

[2 3 4 4 5 7 8 9]


In [66]:
np.where(b > 25,0,b)
print(np.where(b > 5,0,b)) 

[[1 2 3]
 [4 4 5]
 [0 0 0]]


In [69]:
b.shape

(3, 3)

In [71]:
b.dtype

dtype('int64')

In [72]:
b.size

9

In [73]:
b.ndim

2

In [74]:
b+10

array([[11, 12, 13],
       [14, 14, 15],
       [17, 18, 19]])

In [75]:
b*0

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [77]:
b.T

array([[1, 4, 7],
       [2, 4, 8],
       [3, 5, 9]])

In [78]:
a @ b

array([30, 34, 40])

In [82]:
b.min(axis=0)


array([1, 2, 3])

In [83]:
b.min(axis=1)

array([1, 4, 7])

In [87]:
import pandas as pd

In [89]:
df = pd.DataFrame({
  'day': ['1/1/2017', '1/2/2017'],
  'temperature': [32, 35],
  'windspeed': [6, 7],
  'event': ['Rain', 'Sunny']
})
print(df)

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny


In [91]:
df=pd.read_csv("nyc_weather.csv")
print(df)

          EST  Temperature  DewPoint  Humidity  Sea Level PressureIn  \
0    1/1/2016           38        23        52                 30.03   
1    1/2/2016           36        18        46                 30.02   
2    1/3/2016           40        21        47                 29.86   
3    1/4/2016           25         9        44                 30.05   
4    1/5/2016           20        -3        41                 30.57   
5    1/6/2016           33         4        35                 30.50   
6    1/7/2016           39        11        33                 30.28   
7    1/8/2016           39        29        64                 30.20   
8    1/9/2016           44        38        77                 30.16   
9   1/10/2016           50        46        71                 29.59   
10  1/11/2016           33         8        37                 29.92   
11  1/12/2016           35        15        53                 29.85   
12  1/13/2016           26         4        42                 2

In [104]:
df.head(31)

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,1/1/2016,38,23,52,30.03,10,8.0,0,5,NaN,281
1,1/2/2016,36,18,46,30.02,10,7.0,0,3,NaN,275
2,1/3/2016,40,21,47,29.86,10,8.0,0,1,NaN,277
3,1/4/2016,25,9,44,30.05,10,9.0,0,3,NaN,345
4,1/5/2016,20,-3,41,30.57,10,5.0,0,0,NaN,333
5,1/6/2016,33,4,35,30.50,10,4.0,0,0,NaN,259
6,1/7/2016,39,11,33,30.28,10,2.0,0,3,NaN,293
7,1/8/2016,39,29,64,30.20,10,4.0,0,8,NaN,79
8,1/9/2016,44,38,77,30.16,9,8.0,T,8,Rain,76
9,1/10/2016,50,46,71,29.59,4,NaN,1.8,7,Rain,109


In [96]:
df.tail(5)

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
26,1/27/2016,41,22,45,30.03,10,7.0,T,3,Rain,311
27,1/28/2016,37,20,51,29.90,10,5.0,0,1,NaN,234
28,1/29/2016,36,21,50,29.58,10,8.0,0,4,NaN,298
29,1/30/2016,34,16,46,30.01,10,7.0,0,0,NaN,257
30,1/31/2016,46,28,52,29.90,10,5.0,0,0,NaN,241


In [97]:
df.shape

(31, 11)

In [98]:
df.columns

Index(['EST', 'Temperature', 'DewPoint', 'Humidity', 'Sea Level PressureIn',
       'VisibilityMiles', 'WindSpeedMPH', 'PrecipitationIn', 'CloudCover',
       'Events', 'WindDirDegrees'],
      dtype='str')

In [99]:
df.dtypes

EST                         str
Temperature               int64
DewPoint                  int64
Humidity                  int64
Sea Level PressureIn    float64
VisibilityMiles           int64
WindSpeedMPH            float64
PrecipitationIn             str
CloudCover                int64
Events                      str
WindDirDegrees            int64
dtype: object

In [105]:
df.describe()

,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,CloudCover,WindDirDegrees
count,31.000000,31.000000,31.000000,31.000000,31.000000,28.000000,31.000000,31.000000
mean,34.677419,17.838710,51.677419,29.992903,9.193548,6.892857,3.129032,247.129032
std,7.639315,11.378626,11.634395,0.237237,1.939405,2.871821,2.629853,92.308086
min,20.000000,-3.000000,33.000000,29.520000,1.000000,2.000000,0.000000,34.000000
25%,29.000000,10.000000,44.500000,29.855000,9.000000,5.000000,1.000000,238.000000
50%,35.000000,18.000000,50.000000,30.010000,10.000000,6.500000,3.000000,281.000000
75%,39.500000,23.000000,55.000000,30.140000,10.000000,8.000000,4.500000,300.000000
max,50.000000,46.000000,78.000000,30.570000,10.000000,16.000000,8.000000,345.000000


In [103]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   EST                   31 non-null     str    
 1   Temperature           31 non-null     int64  
 2   DewPoint              31 non-null     int64  
 3   Humidity              31 non-null     int64  
 4   Sea Level PressureIn  31 non-null     float64
 5   VisibilityMiles       31 non-null     int64  
 6   WindSpeedMPH          28 non-null     float64
 7   PrecipitationIn       31 non-null     str    
 8   CloudCover            31 non-null     int64  
 9   Events                9 non-null      str    
 10  WindDirDegrees        31 non-null     int64  
dtypes: float64(2), int64(6), str(3)
memory usage: 2.8 KB


In [106]:
df.isnull().sum()

EST                      0
Temperature              0
DewPoint                 0
Humidity                 0
Sea Level PressureIn     0
VisibilityMiles          0
WindSpeedMPH             3
PrecipitationIn          0
CloudCover               0
Events                  22
WindDirDegrees           0
dtype: int64

In [ ]:
df[['Temperature','EST']]

In [112]:
df.EST

0      1/1/2016
1      1/2/2016
2      1/3/2016
3      1/4/2016
4      1/5/2016
5      1/6/2016
6      1/7/2016
7      1/8/2016
8      1/9/2016
9     1/10/2016
10    1/11/2016
11    1/12/2016
12    1/13/2016
13    1/14/2016
14    1/15/2016
15    1/16/2016
16    1/17/2016
17    1/18/2016
18    1/19/2016
19    1/20/2016
20    1/21/2016
21    1/22/2016
22    1/23/2016
23    1/24/2016
24    1/25/2016
25    1/26/2016
26    1/27/2016
27    1/28/2016
28    1/29/2016
29    1/30/2016
30    1/31/2016
Name: EST, dtype: str

In [113]:
df[1:4 ]

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
1,1/2/2016,36,18,46,30.02,10,7.0,0,3,NaN,275
2,1/3/2016,40,21,47,29.86,10,8.0,0,1,NaN,277
3,1/4/2016,25,9,44,30.05,10,9.0,0,3,NaN,345


In [115]:
df.iloc[3]

EST                     1/4/2016
Temperature                   25
DewPoint                       9
Humidity                      44
Sea Level PressureIn       30.05
VisibilityMiles               10
WindSpeedMPH                 9.0
PrecipitationIn                0
CloudCover                     3
Events                       NaN
WindDirDegrees               345
Name: 3, dtype: object

In [117]:
df[df['Temperature']>40]

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
8,1/9/2016,44,38,77,30.16,9,8.0,T,8,Rain,76
9,1/10/2016,50,46,71,29.59,4,NaN,1.8,7,Rain,109
14,1/15/2016,43,31,62,29.82,9,5.0,T,2,NaN,101
15,1/16/2016,47,37,70,29.52,8,7.0,0.24,7,Rain,340
25,1/26/2016,43,29,56,30.03,10,7.0,0,2,NaN,244
26,1/27/2016,41,22,45,30.03,10,7.0,T,3,Rain,311
30,1/31/2016,46,28,52,29.90,10,5.0,0,0,NaN,241
