In [2]:
import numpy as np

In [3]:
a = np.array([1, 2, 3])
m = np.array([[1,2],[3,4]])

In [4]:
a = np.array([1,2,3])
m = np.array([[1,2],[3,4]])


In [7]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [18]:
np.random.rand(3,3)       

array([[0.07530676, 0.35235682, 0.87650043],
       [0.38367435, 0.39909373, 0.1329385 ],
       [0.67591253, 0.73120245, 0.4300439 ]])

In [22]:
np.random.randn(2,2)

array([[-0.88099696,  0.88193053],
       [ 0.11753666, -0.76920321]])

In [35]:
np.random.randint(1,20,(4,4))

array([[ 4, 18,  5, 17],
       [19,  7,  1,  8],
       [ 5, 18, 10, 12],
       [ 9, 16, 13,  1]], dtype=int32)

In [36]:
np.arange(0,14,3)

array([ 0,  3,  6,  9, 12])